language: c

compiler:
  - clang
  - gcc

before_script:
  - cmake .
  - make YASL
  - make YASLTEST
  - make yaslapi

script:
  - ./tests 

addons:
  apt:
    packages:
      - valgrind
      
notifications: 
  email: false 
