# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

jobs:
- job: 
  displayName: "C GCC Ubuntu"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script:
      sudo apt install valgrind
    displayName: "Install Valgrind"  
  - script: |
      cmake .
      make YASL
      make YASLTEST
      make yaslapi
    displayName: "Compile"
  - script:
      ./tests
    displayName: "Run Tests"
- job: 
  displayName: "C++ GCC Ubuntu"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script:
      sudo apt install valgrind
    displayName: "Install Valgrind"  
  - script: |
      cmake -Dcpp=true
      cmake .
      make YASL
      make YASLTEST
      make yaslapi
    displayName: "Compile"
  - script:
      ./tests
    displayName: "Run Tests"  
