# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script:
    sudo apt install valgrind

- script: |
    cmake .
    make YASL
    make YASLTEST
    make yaslapi

- script:
    ./tests -m
